### ISSUE TITLE
Traefik 2.0 upgrade after load balancer not working

### ISSUE THREAD

**Issue by safakseyrek** [vegasbrianc/docker-traefik-prometheus#18]
Hi,
I've completed the set up correctly, but the cats project is working with 3 replicas. When requesting Cats application, only 1 container returns response. Other containers bad gateway.

You can try it (10x times refresh page) you will see: 
http://cats.taigalab.com/

**Comment by vegasbrianc** [comment]
Hi @safakseyrek Thanks for your comment. I left some testing code in place `rate-limit` which kills the connections if too many requests come. I have commented on this feature and it should work normally again.

Thanks again for finding this.

https://github.com/vegasbrianc/docker-traefik-prometheus/pull/19

**Comment by safakseyrek** [comment]
Hi, @vegasbrianc bug not fixed. 
Active now. Try again this;
http://cats.taigalab.com/

**Comment by vegasbrianc** [comment]
@safakseyrek Can you post all of your configs?

**Comment by safakseyrek** [comment]
I have 3 virtual machine. 1 leader 2 worker.

docker-compose.yml
`version: '3.7'

services:
  traefik:
    image: traefik:v2.0.4
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.watch"
    networks:
      - traefik
      - inbound
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - inbound
    deploy:
      labels:
       - "traefik.http.routers.prometheus.rule=Host(`prometheus.taigalab.com`)"
       - "traefik.http.routers.prometheus.service=prometheus"
       - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
       - "traefik.docker.network=inbound"
      placement:
        constraints:
        - node.role==manager
      restart_policy:
        condition: on-failure
  
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - inbound
    user: "104"
    deploy:
      labels:
        - "traefik.http.routers.grafana.rule=Host(`grafana.taigalab.com`)"
        - "traefik.http.routers.grafana.service=grafana"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        - "traefik.docker.network=inbound"
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  traefik:
    driver: overlay
    name: traefik
  inbound:
    driver: overlay
    name: inbound

volumes:
    prometheus_data: {}
    grafana_data: {}`


cats.yml

`version: '3.7'

services:
  cat-app:
    image: mikesir87/cats
    networks:
      - inbound
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.http.routers.cat-app.rule=Host(`cats.taigalab.com`)"
        - "traefik.http.routers.cat-app.service=cat-app"
        - "traefik.http.services.cat-app.loadbalancer.server.port=5000"
        - "traefik.docker.network=inbound"
        # Remove the line below to enable rate limiting. This will only allow avergae 1 request per second before erroring.
      #  - "traefik.http.routers.cat-app.middlewares=cat-app@docker"
      #  - "traefik.http.middlewares.cat-app.ratelimit.average=1"
networks:
  inbound:
   external: true`

**Comment by safakseyrek** [comment]
Sorry. I found the problem. The firewall between the virtual machines is blocking the connection.
