### ISSUE TITLE
Alerting and some configs

### ISSUE THREAD

**Issue by J88G** [vegasbrianc/docker-traefik-prometheus#21]
Hi! Thanks for the great repository.

Could you explain me few things please
- how can I configure the alert manager with slack for prometheus?
- how can I add basic auth for those services (prometheus, traefik, alert manager) ? 
- is it possible to serve Traefik in the same way as the other services ? example - traefik.localhost 
- Can we remove close the port 8080?

Thanks in advance

**Comment by vegasbrianc** [comment]
HI @J88G Somehow i missed your issue.

- This tutorial explains the integration the best - https://www.robustperception.io/using-slack-with-the-alertmanager
- Basic Auth can be handled by Traefik. You can add the middleware basicAuth and the label to each service you want to use it with. https://docs.traefik.io/middlewares/basicauth/
- You can setup up the domain also for the dashboard - https://docs.traefik.io/operations/dashboard/#dashboard-router-rule
- You can use the same entrypoint as HTTP or HTTPS if needed
